[env:nodemcuv2]

platform = espressif8266@4.2.1
board = nodemcuv2
framework = arduino

monitor_speed = 115200

; ---------------------------------------------------
; Source files are kept directly in repository root
; ---------------------------------------------------

src_dir = .

build_src_filter =
    +<*.cpp>
    -<.pio/>
    -<.piofs/>
    -<.github/>

; ---------------------------------------------------
; LittleFS
; ---------------------------------------------------

board_build.filesystem = littlefs

; 4 MB flash / 1 MB filesystem
board_build.ldscript = eagle.flash.4m1m.ld

; ---------------------------------------------------
; Prepare root web files before LittleFS build
; ---------------------------------------------------

extra_scripts = pre:prepare_fs.py

; ---------------------------------------------------
; Libraries
; ---------------------------------------------------

lib_deps =
    bblanchon/ArduinoJson @ ^7.4.2

; ---------------------------------------------------
; ESP8266 configuration
; ---------------------------------------------------

build_flags =
    -DPIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY
    -DVTABLES_IN_FLASH
