[platformio]
src_dir = .
data_dir = .piofs

[env:nodemcuv2]
platform = espressif8266@4.2.1
board = nodemcuv2
framework = arduino

monitor_speed = 115200

; Compile only C/C++ source files from repository root.
build_src_filter =
    +<*.cpp>
    -<.pio/>
    -<.piofs/>

; LittleFS filesystem
board_build.filesystem = littlefs

; Prepare temporary filesystem before build
extra_scripts = pre:prepare_fs.py

lib_deps =
    bblanchon/ArduinoJson @ ^7.4.2

build_flags =
    -DPIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY
    -DVTABLES_IN_FLASH
